import Head from "next/head"

type Props = {
    title?: string
};
export const GlobalHeader = (props: Props) => {
    return (
        <Head>
            <title>{props.title || "Party Page"}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}