/** @jsxImportSource @emotion/react */
import React, {useState, useEffect} from "react";
import type { NextPage } from 'next';
import Head from 'next/head';
// Styles
import * as style_index from '../styles/project/index';
import * as style_quiz from '../styles/project/quiz';
import * as style_utility from '../styles/utility/utility'
import * as style_btn from '../styles/components/sbtn'

const Home:NextPage = () => {


  return (
    <div css={style_utility.color_bg}>
    <Head>
        <title>User's Page!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

    <main css={style_index.Container}>
      <h2 css={[style_index.title, style_utility.mb30]}>Party</h2>
      <p css={[style_index.questionTitle, style_utility.mb30]}>お寿司はどれ</p>
      <section css={style_index.CardsWrap}>
        <button css={[style_btn.StylePrimaryBtn, style_index.CardWrap ,style_utility.mb30]}>A</button>
        <button css={[style_btn.StyleDangerBtn, style_index.CardWrap ,style_utility.mb30]}>B</button>
        <button css={[style_btn.StyleSuccessBtn, style_index.CardWrap ,style_utility.mb30]}>C</button>
        <button css={[style_btn.StyleWarningBtn, style_index.CardWrap ,style_utility.mb30]}>D</button>
    </section>
    </main>
    <style jsx>{`
        .bg-primary {
            background-color: #527FC2;
        }
        .bg-danger {
            background-color: #C25252;
        }
        .bg-success {
            background-color: #52C256;
        }
        .bg-warning {
            background-color: #C2B752;
        }
    `}</style>
    </div>
    
  )

}

export default Home